### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by unclead** [webtoucher/yii2-amqp#12]
- [ ] Refactor the code
- [ ] Write tests
- [ ] Update docs
- [ ] Write examples

**Comment by thiagotalma** [comment]
Hello @unclead 

Any news here?

cc: @webtoucher

**Comment by unclead** [comment]
hi. nope :disappointed: The repo is abadoned IMO
If you have any ideas we glad to hear them

**Comment by unclead** [comment]
I think we can port https://github.com/php-amqplib/RabbitMqBundle library on yii2 because current implementation was made for solving our problems on internal projects

**Comment by wapmorgan** [comment]
Need any release to point in requirements.
